"""Stable values used by the LinkedIn connection RPA."""

GOOGLE_CHROME_BINARY = "/usr/bin/google-chrome"

LINKEDIN_HOME_URL = "https://www.linkedin.com/feed/"
LINKEDIN_MY_NETWORK_URL = "https://www.linkedin.com/mynetwork/"
LINKEDIN_GROW_URL = "https://www.linkedin.com/mynetwork/grow/"

CONNECT_LABEL = "Conectar"
PENDING_LABEL = "Pendente"

DEFAULT_WAIT_SECONDS = 15
DEFAULT_SCROLL_PAUSE_SECONDS = 1.0
DEFAULT_DAILY_CONNECTION_LIMIT = 10
DEFAULT_MIN_INVITATION_PAUSE_SECONDS = 3.0
DEFAULT_MAX_INVITATION_PAUSE_SECONDS = 8.0
DEFAULT_BATCH_SIZE = 10
DEFAULT_MIN_BATCH_PAUSE_SECONDS = 30.0
DEFAULT_MAX_BATCH_PAUSE_SECONDS = 60.0
MAX_SCROLL_ATTEMPTS_WITHOUT_CLICK = 12
DEFAULT_MAX_BROWSER_RESTARTS_WITHOUT_SUGGESTIONS = 1
